### ISSUE TITLE
Drop down menus and DFU mode inoperable

### ISSUE THREAD

**Issue by ToxicityKingETN** [liamcottle/rnode-flasher#1]
All drop down menus provide no options, not able to select anything, making this tool unusable.
I appreciate your work, and I hope a resolution can be made. Thank you!

Windows 11
Google chrome attempted
Internet explorer attempted
Firefox attempted
Microsoft edge attempted

**Comment by liamcottle** [comment]
Sounds funky... Could you open the dev tools console, reload the page and see if there's any errors? :)

**Comment by ToxicityKingETN** [comment]
![Screenshot 2024-10-13 222845](https://github.com/user-attachments/assets/16d30b9c-e2f9-4629-bd8b-8a2c39efd0c6)
Many lol

**Comment by liamcottle** [comment]
My bad, I'll need to update the readme. You can no longer just double click the index.html you downloaded. (When I first released the project, it was possible since I didn't have any .js files)

Browsers will not allow you to load script files locally when you load the page over the `file:///` protocol.

I'd suggest using the hosted web flasher for now, otherwise you'll need to run a web server to serve the files properly to make the browser happy. Something like `python3 -m http.server 8080` might do the trick...

https://liamcottle.github.io/rnode-flasher/

**Comment by ToxicityKingETN** [comment]
Ah lol, I was like hmmmmm. Thanks for the reply
